apiVersion: retina.sh/v1alpha1
kind: Capture
metadata:
  name: samplecrdcapture2
spec:
  captureConfiguration:
    captureOption:
      duration: "30s"
    captureTarget:
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: demo
      podSelector: 
        matchLabels:
          org: retina
  outputConfiguration:
    blobUpload: cblob-sas-url

